### PR TITLE
Update compiler version to 2024-07-25 (rust 1.80)

### PR DESCRIPTION
**Pull request by nsarlin-zama**
Bump the compiler version.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Sorry, I'm a bit under the water lately. ^^'

Gonna try to take a look at it tomorrow. In the meantime I started the CI.

**Comment by GuillaumeGomez** [comment]
CI still unhappy.

**Comment by nsarlin-zama** [comment]
> CI still unhappy.

I think the workflow needs to be updated, it does a `git checkout v0.78.0` on the example repo

**Comment by GuillaumeGomez** [comment]
Ah I see. Do you mind pushing it to this PR please?

**Comment by nsarlin-zama** [comment]
I've removed the checkout in the workflow to make the CI work on the PR, but maybe if it's green you might want to add a new tag on the example repo that I can use before merging this ?

**Comment by GuillaumeGomez** [comment]
I'm not sure why I added a tag in the first place to check it out in this CI. I'm also thinking more and more that I should move examples in this repository to make things simpler.

In any case, CI is happy. Great job, thanks!

I want to rework the API a bit so release will wait until it's done, should be fast. Just need to find one hour to do it. ^^'

**Comment by GuillaumeGomez** [comment]
Just released the `0.80.0` version of the crate. Enjoy! Gonna update docs shortly.

**Pull request merged**
